### ISSUE TITLE
Help identifying DynamobDB scenarios important for .NET developers

### ISSUE THREAD

**Issue by ebattalio** [awsdocs/aws-guide-for-net-developers#1]
Do you use AWS DynamoDB and .NET in your application? Are you thinking about using DynamoDB and .NET for your data storage needs?

Help us improve the AWS Guide for .NET Developers by:

* Sharing your scenario or content needs or by contributing code samples
* Contributing an illustrative code sample
* Sharing how-to steps, conceptual content, or other insights

*You can reply directly to this thread. For updates and additions, you can fork the repo, make your changes and then submit a pull request. All helpful contributions are appreciated!*

**Comment by Doug-AWS** [comment]
No replies in over a year. closing.
