### ISSUE TITLE
Make AWS Doc open source

### ISSUE THREAD

**Issue by hanslai** [awsdocs/aws-guide-for-net-developers#11]
I will suggest make all the AWS guide/ docs open source in github.  Just like what Microsoft did.

ex, https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-3.0

With the community's help, I can see how its documentation improved over the past 2 years.

**Comment by Doug-AWS** [comment]
We have all of our docs open source.

**Comment by hanslai** [comment]
@Doug-AWS Thanks.  Sorry about that, I should have check first.
Yet, the MS Doc is a lot more obvious, it is easier for the community to participate I think.

Form their  Doc, user can jump right into the doc's github page.  This is  nice for AWS Doc to have as well I believe.  Please see image below.
![B7B15E98-50DE-49b5-BD1D-7675C0651B6B](https://user-images.githubusercontent.com/20576491/61878670-fde6fa80-af23-11e9-987c-0040a725989f.png)
![8703EF09-2DF0-45e9-BCB6-2D2F43BCB788](https://user-images.githubusercontent.com/20576491/61878673-ff182780-af23-11e9-9cb0-bbc200ead0d8.png)

**Comment by Doug-AWS** [comment]
We have that also:

![image](https://user-images.githubusercontent.com/16107690/61883211-dbff6080-aeae-11e9-854b-f9ad7ecd49ed.png)

**Comment by Doug-AWS** [comment]
We have that also:

![image](https://user-images.githubusercontent.com/16107690/61883349-2254bf80-aeaf-11e9-9b3e-773819d9aeea.png)
