### ISSUE TITLE
Tips, tricks, and gotchas for writing async code with the AWS .NET SDK

### ISSUE THREAD

**Issue by ebattalio** [awsdocs/aws-guide-for-net-developers#2]
More and more .NET developers are using asynchronous code to improve application performance and responsiveness...or because it is required as with .NET Core.

**If you have experience using the AWS .NET SDK with asynchronous code**, share your tips, tricks and gotchas. What works, what doesn't work, and where are the gotchas? Was a "gotcha" missing content (and if so, what is it)? Are there helpful blog post or other sources (links)?

**If you are just getting started**, share what you need to be successful using async and the AWS .NET SDK. Code samples, conceptual documentation, specific AWS service scenarios, walk-throughs -- what would help most?

*You can reply directly to this thread. For updates and additions, you can fork the repo, make your changes and then submit a pull request. All helpful contributions are appreciated!*

**Comment by Doug-AWS** [comment]
No replies in over a year. Closing.
