### ISSUE TITLE
What would you like to see in the AWS Guide?

### ISSUE THREAD

**Issue by ebattalio** [awsdocs/aws-guide-for-net-developers#3]
The AWS Guide for .NET Developers is a work-in-progress, dependent on feedback from the AWS .NET developer community to evolve. 

You can help. Suggest future content by opening a *New issue*, entering the details of your request, tagging it "Enhancement" and then clicking *Submit new issue*. 

It is that easy!

**Comment by Doug-AWS** [comment]
No replies in over a year, closing.

**Comment by hanslai** [comment]
Make the guide open source. #11
