### ISSUE TITLE
[Enhancement] Request code example for AmazonLambdaClient.CreateFunction()

### ISSUE THREAD

**Issue by alanmur** [awsdocs/aws-guide-for-net-developers#5]
I am trying to use AmazonLambdaClient.CreateFunction to deploy a lambda. How to provide the ZipFile to the CreateFunctionRequest is proving elusive and I didn't find a suitable example of its use anywhere.

**Comment by pccornel** [comment]
Thanks for the request. I'll add this to the team's backlog for future consideration. 

Paul
AWS Documentation
