### ISSUE TITLE
Help Wanted - Please Submit Examples for Your Common Scenarios!

### ISSUE THREAD

**Issue by bisdavid** [awsdocs/aws-guide-for-net-developers#6]
Hey everyone! We're always on the lookout for good examples that illustrate "best practices" for performing common tasks using the AWS .NET SDK. We provide as many samples as we can when we first publish a guide, but only you know what you automate using the .NET SDK for on a daily basis. What common tasks have you automated with the AWS .NET SDK that others could learn from? Share your examples with us!

Submit a pull request as explained in these directions: https://github.com/awsdocs/aws-guide-for-net-developers/blob/master/CONTRIBUTING.md

Thank you!
Dave Bishop

**Comment by Doug-AWS** [comment]
No responses == closing.
